import React from "react";
import Footer from "./Footer";
import Header from "./Header";
import Head from "next/head";

import 'bootstrap/dist/css/bootstrap.css';

const Layout = ({ children, title }) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      
      </Head>

      <Header />
      {children}
      <Footer />
    </div>
  );
};

export default Layout;
